### PR TITLE
Fix macro redefinition and include common_cmake_config.h errors

### PR DESCRIPTION
**Pull request by zheqiMicrosoft**
Duplicate of Patrto's PR(https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/81). So we can get it merged and unblocked.

### CODE REVIEW

**Comment by zheqiMicrosoft** [comment]
Build warning occurs when NOMINMAX or WIN32_LEAN_AND_MEAN is already defined
If the loader files are generated without cmake, common_cmake_config.h doesn't exist so its inclusion should be wrapped around a macro.

**Comment by patrto** [comment]
@zheqiMicrosoft is uploading this instead of me so we can get unblocked, as I'm waiting for confirmation that I can sign the CLA. Thank you!

**Comment by zheqiMicrosoft** [comment]
google wants headers included alphabetically and loader_interfaces.h depends on openxr.h

**Comment by rpavlik** [comment]
Please don't submit PRs to this repo, submit it to the other one instead. This is a generated repo, GitHub just doesn't give me the option to disable the PR feature.

**Comment by rpavlik** [comment]
Merged in source repo.

**Pull request closed without merging**
